### ISSUE TITLE
Delete fromAll persistent subscription from UI

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore.UI#306]
**Describe the bug**
Attempt to delete a fromAll Persistent Subscription from the UI

**To Reproduce**
1. Hit delete on the fromAll Perisistent subscription

**Expected behavior**
Susbcription should be deleted.

**Actual behavior**
![image](https://user-images.githubusercontent.com/13871941/150331417-605a1b99-8c00-4303-b518-90884a716692.png)

**Config/Logs/Screenshots**

![image](https://user-images.githubusercontent.com/13871941/150331328-e94f1b61-5f98-4cf9-b6eb-a2ba6081c414.png)

*EventStore details**
 - EventStore server version: 21.6

**Comment by oskardudycz** [comment]
@StevenBlair123, as was noted in the [21.10 release notes](https://www.eventstore.com/blog/21.10.0-release-notes), persistent subscriptions to $all management is only supported through the gRPC client. We won't provide that feature at the moment. However, I think that we should improve UI to be explicit about that.

I transferred the issue to the EventStoreDB UI repo, I hope that at least this enigmatic error will be fixed in the next version.

**Comment by hayley-jean** [comment]
We should disable the delete and update buttons for persistent subscriptions to $all in the UI to prevent this from happening.

**Comment by lakshdeepsingheventstore** [comment]
As mentioned above, I cannot see the "Edit" and "Delete" buttons for persistent subscriptions to $all in the UI, as seen in the screenshot attached below. Created a PS to the $all stream using the Java Client. 

![image](https://user-images.githubusercontent.com/88392797/163867954-a991ef96-383f-437e-b7f0-8b825b14102f.png)
